/* Comb-field rect correction. Loaded after js/field-maps.js and BEFORE
   js/app.js builds the ATO overlays.

   Kept separate because field-maps.js is generated by scripts/build_maps.py and
   marked do-not-edit; patching here survives a regeneration. The durable fix is
   to have build_maps.py derive rects from the drawn boxes in the first place.

   Every comb field stored the AcroForm WIDGET rect, which the ATO insets from
   the box the form actually draws (~1.2-2pt, and 12pt of width on the two
   state fields). Cells are stored as absolute x-ranges and positioned as a
   percentage of that rect, so an inset rect skewed the whole overlay: most
   visibly the TFN date of birth, whose rect was 14.3pt tall against a drawn
   box of 16.5pt.

   Values below are measured straight from the source PDFs with PyMuPDF: for
   each field, the union of the boxes its own cells sit in. Verified against
   the declaration date, whose rect already matched its boxes exactly and
   which rendered correctly before this patch. */
(function () {
    "use strict";
    if (!window.FIELD_MAPS || !window.FIELD_MAPS.docs) return;

    var FIX = {
            "tfn": {
                    "1-TFN": [
                            136.3,
                            93.79,
                            290.3,
                            110.3
                    ],
                    "2-familyName": [
                            22.9,
                            218.52,
                            290.3,
                            235.03
                    ],
                    "2-firstName": [
                            22.9,
                            245.45,
                            290.3,
                            261.96
                    ],
                    "2-otherName": [
                            22.9,
                            272.38,
                            290.3,
                            288.88
                    ],
                    "3-addressLine1": [
                            22.9,
                            310.64,
                            290.3,
                            327.15
                    ],
                    "3-addressLine2": [
                            22.9,
                            334.74,
                            290.3,
                            351.25
                    ],
                    "3-addressSuburb": [
                            22.9,
                            360.25,
                            290.3,
                            376.76
                    ],
                    "3-addressState": [
                            22.9,
                            385.76,
                            77.6,
                            402.29
                    ],
                    "3-addressPostcode": [
                            93.8,
                            385.76,
                            148.6,
                            402.27
                    ],
                    "4-nameChange": [
                            22.9,
                            432.78,
                            290.3,
                            449.29
                    ],
                    "5-addressLine1": [
                            316.3,
                            93.79,
                            583.7,
                            110.24
                    ],
                    "5-addressLine2": [
                            316.3,
                            119.24,
                            583.7,
                            135.69
                    ],
                    "4-dateDay": [
                            455.2,
                            151.2,
                            481.6,
                            167.7
                    ],
                    "4-dateMonth": [
                            492.1,
                            151.2,
                            518.5,
                            167.7
                    ],
                    "4-dateYear": [
                            528.9,
                            151.2,
                            583.7,
                            167.7
                    ],
                    "b1-ABN": [
                            22.9,
                            513.0,
                            219.4,
                            529.5
                    ],
                    "b1-branchNumber": [
                            244.0,
                            513.0,
                            284.6,
                            529.5
                    ],
                    "b3-nameLine1": [
                            23.0,
                            584.0,
                            290.3,
                            600.5
                    ],
                    "b3-nameLine2": [
                            23.0,
                            608.1,
                            290.3,
                            624.6
                    ],
                    "b3-nameLine3": [
                            23.0,
                            632.19,
                            290.3,
                            648.69
                    ],
                    "b4-addressLine1": [
                            23.0,
                            667.93,
                            290.3,
                            684.38
                    ],
                    "b4-addressLine2": [
                            23.0,
                            693.38,
                            290.3,
                            709.83
                    ],
                    "b4-addressSuburb": [
                            23.0,
                            720.28,
                            290.3,
                            736.73
                    ],
                    "b4-addressState": [
                            22.9,
                            745.78,
                            77.9,
                            762.25
                    ],
                    "b4-addressPostcode": [
                            93.8,
                            745.78,
                            148.6,
                            762.23
                    ],
                    "b5-nameLine1": [
                            316.3,
                            503.08,
                            583.7,
                            519.53
                    ],
                    "b5-nameLine2": [
                            316.3,
                            528.53,
                            583.7,
                            544.98
                    ],
                    "b5-contactPerson": [
                            316.3,
                            564.18,
                            583.7,
                            580.68
                    ],
                    "b5-contactPhone": [
                            401.3,
                            588.28,
                            541.2,
                            604.78
                    ]
            },
            "super": {
                    "A-EmployeeNo": [
                            307.8,
                            436.43,
                            532.7,
                            452.94
                    ],
                    "A-TFN": [
                            307.8,
                            474.91,
                            461.8,
                            491.42
                    ],
                    "B-ABN": [
                            28.6,
                            203.78,
                            225.1,
                            220.29
                    ],
                    "B-USI": [
                            28.6,
                            242.26,
                            225.1,
                            258.77
                    ],
                    "B-MemberAccNo": [
                            28.6,
                            313.64,
                            253.5,
                            330.15
                    ],
                    "B-Day": [
                            426.9,
                            641.64,
                            453.3,
                            658.15
                    ],
                    "B-Month": [
                            469.4,
                            641.64,
                            495.8,
                            658.15
                    ],
                    "B-Year": [
                            511.9,
                            641.64,
                            566.7,
                            658.15
                    ],
                    "C-ABN": [
                            48.4,
                            202.03,
                            244.9,
                            218.54
                    ],
                    "C-SuperABN": [
                            48.4,
                            278.99,
                            244.9,
                            295.5
                    ],
                    "C-USI": [
                            48.4,
                            317.48,
                            244.9,
                            333.98
                    ],
                    "C-Day": [
                            426.9,
                            526.38,
                            453.3,
                            542.89
                    ],
                    "C-Month": [
                            469.4,
                            526.38,
                            495.8,
                            542.89
                    ],
                    "C-Year": [
                            511.9,
                            526.38,
                            566.7,
                            542.89
                    ],
                    "D-ABN": [
                            28.6,
                            135.13,
                            225.1,
                            151.64
                    ],
                    "D-BSB": [
                            28.6,
                            360.86,
                            111.7,
                            377.37
                    ],
                    "D-accountNumber": [
                            28.6,
                            399.35,
                            168.4,
                            415.85
                    ],
                    "D-Day": [
                            426.9,
                            580.05,
                            453.3,
                            596.56
                    ],
                    "D-Month": [
                            469.4,
                            580.05,
                            495.8,
                            596.56
                    ],
                    "D-Year": [
                            511.9,
                            580.05,
                            566.7,
                            596.56
                    ]
            }
    };

    var applied = 0;
    window.FIELD_MAPS.docs.forEach(function (doc) {
        var byId = FIX[doc.key];
        if (!byId) return;
        doc.fields.forEach(function (f) {
            if (byId[f.id]) { f.rect = byId[f.id].slice(); applied++; }
        });
    });
    if (window.console) console.log("[preview] field-map rects corrected:", applied);
})();
